---
spring:
    application:
        name: J17-Epractice

j17:
    answers:
        "1":
            - A
        "2":
            - D
        "3":
            - C
        "4":
            - A
        "5":
            - B
        "6":
            - E
        "7":
            - C
        "8":
            - B
        "9":
            - D
        "10":
            - C
        "11":
            - D
        "12":
            - D
        "13":
            - C
        "14":
            - D
        "15":
            - B
        "16":
            - B
        "17":
            - F
        "18":
            - D
        "19":
            - D
        "20":
            - A
        "21":
            - D
        "22":
            - D
        "23":
            - C
        "24":
            - A
        "25":
            - C
            - D
        "26":
            - A
        "27":
            - B
        "28":
            - D
        "29":
            - D
        "30":
            - D
        "31":
            - B
        "32":
            - A
        "33":
            - A
        "34":
            - B
        "35":
            - B
        "36":
            - A
            - E
        "37":
            - B
            - F
        "38":
            - B
        "39":
            - A
            - B
        "40":
            - A
            - E
        "41":
            - B
        "42":
            - E
        "43":
            - D
        "44":
            - D
        "45":
            - D
        "46":
            - B
            - C
        "47":
            - D
        "48":
            - B
        "49":
            - A
        "50":
            - B
